# Generated by Django 2.2.4 on 2022-06-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Wish',
        ),
    ]
