# Generated by Django 2.2.4 on 2022-06-25 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examApp', '0002_auto_20220625_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='users_list',
        ),
        migrations.CreateModel(
            name='grantedwish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('wisher', models.CharField(max_length=35)),
                ('dateadded', models.DateField()),
                ('dategranted', models.DateField()),
                ('likes', models.CharField(max_length=25)),
                ('totalgranted', models.CharField(max_length=35)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creater', to='examApp.User')),
                ('likers', models.ManyToManyField(related_name='liker', to='examApp.User')),
            ],
        ),
        migrations.AddField(
            model_name='wish',
            name='grantedwish',
            field=models.ManyToManyField(related_name='wish', to='examApp.grantedwish'),
        ),
    ]
